### ISSUE TITLE
Haste May return host/None 

### ISSUE THREAD

**Issue by NovaEmiya** [Nimboss2411/ShittyBotty#10]
We are currently returning host/key.get('key') which may return 'host/None', best thing would be using try-except with key["key"], except the error and return an error message instead

**Comment by Nimboss2411** [comment]
_confusion_
what

**Comment by NovaEmiya** [comment]
> _confusion_
> what

https://www.github.com/NovaEmiya/ShittyBotty/tree/main/haste.py
Look what it returns

**Comment by Nimboss2411** [comment]
still confused, try giving me a code example of what you wanna do?

**Comment by NovaEmiya** [comment]
> still confused, try giving me a code example of what you wanna do?

try:
 key = key['key']
except KeyError:
 return "Couldn't upload"#or something better
return f'host/{key}'

**Comment by NovaEmiya** [comment]
@Nimboss2411 fix this before committing too
