### ISSUE TITLE
Clean Code

### ISSUE THREAD

**Issue by NovaEmiya** [Nimboss2411/ShittyBotty#9]
Once the bot is hosted we gonna try cleaning up the code at different parts

**Comment by Nimboss2411** [comment]
"Cleaning the code" as in?

**Comment by NovaEmiya** [comment]
> "Cleaning the code" as in?

Using better ways of doing what the current construct is doing, for efficiency, readability and more

**Comment by Nimboss2411** [comment]
it looks fine to me, what do you suggest-

**Comment by NovaEmiya** [comment]
> it looks fine to me, what do you suggest-

uhh, i'll do it myself
